AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation to launch EC2 (Free Tier) + install Nginx + host static webpage

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP (80) access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro  # Free Tier eligible
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref WebSecurityGroup
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2 AMI (Free Tier, x86_64) – region-specific, this is for us-east-1
      Tags:
        - Key: Name
          Value: WebServer-Nginx
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install nginx1 -y
          systemctl start nginx
          systemctl enable nginx
          echo "<!DOCTYPE html>
          <html>
          <head><title>Welcome</title></head>
          <body>
          <h1>Hello from Nginx on EC2 - SUBHAM 🚀</h1>
          <p>Deployed via AWS CloudFormation 💡</p>
          </body>
          </html>" > /usr/share/nginx/html/index.html

Outputs:
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt WebInstance.PublicIp

  WebsiteURL:
    Description: URL of the hosted website
    Value: !Sub "http://${WebInstance.PublicDnsName}"
